### ISSUE TITLE
Download of story stops

### ISSUE THREAD

**Issue by ProfHariSeldon** [Ackater/writing.com-archival#11]
I left my laptop running overnight for hours and it did not advance beyond 553/5018

Maybe the problem is my computer automatically rebooted (system update) the day before while I was downloading that story, so the download was interrupted

D:\Documents\writing\Archives>C:\Users\linux\AppData\Local\Programs\Python\Python37\python.exe D:\Documents\writing\Archives\writing.com-archival-master\run.py get 1897904-The-dictaphone
### Now archiving 1897904-The-dictaphone
# 1897904-The-dictaphone: Gathering info.
# 1897904-The-dictaphone: Updating with 5018 chapters.
# 1897904-The-dictaphone: 10/5018
# 1897904-The-dictaphone: 17/5018
# 1897904-The-dictaphone: 27/5018
# 1897904-The-dictaphone: 33/5018
# 1897904-The-dictaphone: 43/5018
# 1897904-The-dictaphone: 53/5018
# 1897904-The-dictaphone: 63/5018
# 1897904-The-dictaphone: 70/5018
# 1897904-The-dictaphone: 80/5018
# 1897904-The-dictaphone: 90/5018
# 1897904-The-dictaphone: 96/5018
# 1897904-The-dictaphone: 106/5018
# 1897904-The-dictaphone: 116/5018
# 1897904-The-dictaphone: 126/5018
# 1897904-The-dictaphone: 135/5018
# 1897904-The-dictaphone: 144/5018
# 1897904-The-dictaphone: 154/5018
# 1897904-The-dictaphone: 164/5018
# 1897904-The-dictaphone: 174/5018
# 1897904-The-dictaphone: 184/5018
# 1897904-The-dictaphone: 194/5018
# 1897904-The-dictaphone: 204/5018
# 1897904-The-dictaphone: 214/5018
# 1897904-The-dictaphone: 224/5018
# 1897904-The-dictaphone: 234/5018
# 1897904-The-dictaphone: 244/5018
# 1897904-The-dictaphone: 254/5018
# 1897904-The-dictaphone: 264/5018
# 1897904-The-dictaphone: 274/5018
# 1897904-The-dictaphone: 284/5018
# 1897904-The-dictaphone: 294/5018
# 1897904-The-dictaphone: 296/5018
# 1897904-The-dictaphone: 306/5018
# 1897904-The-dictaphone: 313/5018
# 1897904-The-dictaphone: 323/5018
# 1897904-The-dictaphone: 333/5018
# 1897904-The-dictaphone: 343/5018
# 1897904-The-dictaphone: 353/5018
# 1897904-The-dictaphone: 363/5018
# 1897904-The-dictaphone: 373/5018
# 1897904-The-dictaphone: 383/5018
# 1897904-The-dictaphone: 393/5018
# 1897904-The-dictaphone: 403/5018
# 1897904-The-dictaphone: 413/5018
# 1897904-The-dictaphone: 423/5018
# 1897904-The-dictaphone: 433/5018
# 1897904-The-dictaphone: 443/5018
# 1897904-The-dictaphone: 453/5018
# 1897904-The-dictaphone: 463/5018
# 1897904-The-dictaphone: 473/5018
# 1897904-The-dictaphone: 483/5018
# 1897904-The-dictaphone: 493/5018
# 1897904-The-dictaphone: 503/5018
# 1897904-The-dictaphone: 513/5018
# 1897904-The-dictaphone: 523/5018
# 1897904-The-dictaphone: 533/5018
# 1897904-The-dictaphone: 543/5018
# 1897904-The-dictaphone: 553/5018

**Comment by Ackater** [comment]
Just try again, it should be able to continue where it left off. I downloaded the same story on my Windows setup as a test and it worked fine. Took like 2 hours
