### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by ProfHariSeldon** [Ackater/writing.com-archival#13]
# 1897904-The-dictaphone: 2414/4915
Traceback (most recent call last):
  File "D:\Documents\writing\Archives\writing.com-archival-master\run.py", line 40, in <module>
    args.func(args)
  File "D:\Documents\writing\Archives\writing.com-archival-master\run.py", line 18, in get
    archive(id)
  File "D:\Documents\writing\Archives\writing.com-archival-master\archiver.py", line 89, in archive
    barf(story_root + descent + ".html", formatChapter(chapter,descent,canon_descents))
  File "D:\Documents\writing\Archives\writing.com-archival-master\archiver.py", line 9, in barf
    with open(filepath,'w',encoding='utf-8') as o:
OSError: [Errno 22] Invalid argument: 'archive/1897904-The-dictaphone/134311211111221111112122212211211111211212121221111121111111211111.html'

**Comment by Ackater** [comment]
This seems like an error with the filesystem creating the actual file, hence the "OSError". Can you try manually creating that file? (Delete it afterwards)

**Comment by ProfHariSeldon** [comment]
I reran the download and this happened:

# 1897904-The-dictaphone: 3168/3168
# 1897904-The-dictaphone: Finished with 3168 errors. Try again. If problem persists contact the developer.

**Comment by Ackater** [comment]
Are you on the newest master? Writing.com updated their html and broke the scraper. I updated it with 98a63ac

**Comment by ProfHariSeldon** [comment]
I downloaded the most recent version and it is much better but I still got this:
# 1897904-The-dictaphone: 3604/3604
# 1897904-The-dictaphone: Finished with 1 errors. Try again. If problem persists contact the developer.

**Comment by Ackater** [comment]
Can you run it again so that it will try to download the chapter again? I didn't come across any issues with chapters, but sometimes you'll get a timeout error or something with a request

**Comment by ProfHariSeldon** [comment]
That fixed it, thanks!
