### ISSUE TITLE
"You must type either y or n. [y/n]:" Infinite Loop is back

### ISSUE THREAD

**Issue by HyperPeanut** [Ackater/writing.com-archival#14]
Same as last time while logging in, except now it also has "b'y'" appears along with it.
![Untitled2](https://user-images.githubusercontent.com/50564109/58355030-bf0bca00-7e38-11e9-9411-bb8e498ef5ef.png)

**Comment by Ackater** [comment]
I'm now really confused. Testing this on my own computer, it seems to randomly work and randomly not work.

**Comment by Ackater** [comment]
65c890d seems to work more consistently on my machine now. See if it fixes it for you?

**Comment by HyperPeanut** [comment]
49e8994 fixed it.
