### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by HyperPeanut** [Ackater/writing.com-archival#18]
I honestly don't know what's going on with this. It was working just last week.

![index error](https://user-images.githubusercontent.com/50564109/66265266-5286db80-e7d9-11e9-8e39-a36128acb35a.png)

**Comment by Ackater** [comment]
It's an update on writing.com's side to block the user-agent. I'll update it to spoof Google or something

**Comment by HyperPeanut** [comment]
Now that's just petty. How many people do they think are going to use this utility?

**Comment by Ackater** [comment]
I dont' know if it was targetting this tool or just generic user-agents that don't conform to other's though. As I was using the generic scraper one.

**Comment by Ackater** [comment]
Newest commit should fix this.

**Comment by HyperPeanut** [comment]
Thanks, that worked. Sorry it took so long, I had a massive hardware failure right after you updated.
