### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by azure109** [Ackater/writing.com-archival#19]
![Uploading Untitled.png…]()
Was working one or two weeks ago. no idea why this started.

**Comment by azure109** [comment]
![Untitled](https://user-images.githubusercontent.com/57721532/68782561-94c2f880-0674-11ea-86d7-d1fc2ff45a57.png)

**Comment by Ackater** [comment]
Yes, an update to the website's layout broke the scraper. I've updated the scraper, so please update and try again.

**Comment by azure109** [comment]
It works. Thanks
