### ISSUE TITLE
IndexError: list index out of range [again]

### ISSUE THREAD

**Issue by azure109** [Ackater/writing.com-archival#20]
It happened again. was working like 2 hrs ago then when i tried using it again. it failed
![Untitled](https://user-images.githubusercontent.com/57721532/69221768-063e0200-0bb3-11ea-8376-29fc6be10619.png)

**Comment by Ackater** [comment]
Yes, some names have been changed again to break the scraper. I wonder if it's on purpose now or not.

Try the newest commit

**Comment by azure109** [comment]
it works now. thanks
