### ISSUE TITLE
error in downloading chapters

### ISSUE THREAD

**Issue by azure109** [Ackater/writing.com-archival#21]
There seems to be an error in downloading the chapters
![image](https://user-images.githubusercontent.com/57721532/70642938-16f60b00-1c7b-11ea-800f-e5697c2ad60f.png)

**Comment by Ackater** [comment]
Another layout change. Another update to fix it.

**Comment by azure109** [comment]
Still the same problem.

**Comment by Ackater** [comment]
Still unable to reproduce. I did a fresh download of the same interactive with no problem, though it did take 2 tries.

**Comment by azure109** [comment]
redownloaded the rar file and it seems to be working. thanks
