### ISSUE TITLE
Index Error: list index out of range (again)

### ISSUE THREAD

**Issue by HyperPeanut** [Ackater/writing.com-archival#22]
![Untitled](https://user-images.githubusercontent.com/50564109/71504041-66246a00-283d-11ea-8dbf-578c998dc9d8.png)

**Comment by Ackater** [comment]
Strange, mine seems to be running fine. Did you retry?

**Comment by HyperPeanut** [comment]
Yes and I tried it with several different interactives and it still didn't work.

**Comment by Ackater** [comment]
Mine is still running fine, and I am unable to reproduce. It could be related to your account. Could you try with a new account maybe?

**Comment by bixoa** [comment]
I am having the same issue with interactives.

**Comment by bixoa** [comment]
I [forked the project](https://github.com/bixoa/writing.com-archival) and added files for it to be runnable from within a docker container to show the reproducibility of the problem.

**Comment by HyperPeanut** [comment]
Tried creating a new account, redownloaded the program, and ran it while connected to a vpn. Got the same exact error every time.

**Comment by Ackater** [comment]
Looks like it's an issue with the login. I was using an older session file which was logged in and worked fine

**Comment by Ackater** [comment]
Please try the update, changed the user-agent to a proper one instead of a Google one which seems to fix the login. 

Also @bixoa if you want to submit a pull request I'll merge it in. Though wouldn't it be better to install the python dependencies before copying code? For better caching

**Comment by HyperPeanut** [comment]
It works. Thank you.
