### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by WuJeremy** [Ackater/writing.com-archival#24]
was using the update command then suddenly some errors in download so i deleted session and logged in again.

then suddenly this happens (this was an old version but was working before)
![i](https://user-images.githubusercontent.com/37332188/82987603-5f876200-a02a-11ea-8dd4-7a7f68b0b642.png)

and this is what the current versions response
![image](https://user-images.githubusercontent.com/37332188/82989171-d32a6e80-a02c-11ea-972e-e3ba98c9c280.png)

**Comment by HyperPeanut** [comment]
Getting this issue too.
![Untitled](https://user-images.githubusercontent.com/50564109/83685294-0e3d1c80-a5ae-11ea-8bc9-58d060e58a72.png)

**Comment by Ackater** [comment]
Whoops, just saw this. 2eabff1 should fix this. 

Also I've been working on a rewrite of the scraper, https://ackater.github.io/writing.com-archival/ is how it's looking right now, but it's completely incompatible with the old file format. Do you guys care about that at all?

**Comment by HyperPeanut** [comment]
That worked for me, thanks. Also the rewrite looks pretty good.

**Comment by WuJeremy** [comment]
It works, thanks. best add that in a new repository in case some will want the old file format. the rewrite is easier to read and look at than before.
