### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by HyperPeanut** [Ackater/writing.com-archival#25]
Here we go again.
![aw shit here we go again](https://user-images.githubusercontent.com/50564109/89724712-39882180-d9cc-11ea-94ab-bcc86bbb652c.png)

**Comment by Ackater** [comment]
Try now, looks like they changed the 'temporary unavailable' page

**Comment by HyperPeanut** [comment]
Thanks, It worked. Sorry it took so long, I've been super busy lately.
