### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by azure109** [Ackater/writing.com-archival#31]
seems the error is back
![Untitled](https://user-images.githubusercontent.com/57721532/102228750-016a8f80-3f26-11eb-8b4b-15481fd33021.png)

**Comment by Ackater** [comment]
Writing.com moved some stuff around again, please download the newest version and try again

**Comment by azure109** [comment]
It works now. Thanks. Belated Merry Christmas and a happy new year btw :).
