### ISSUE TITLE
Non-existant story chapter choices are still formatted as links (albeit links without an actual hyperlink?)

### ISSUE THREAD

**Issue by NintendoManiac64** [Ackater/writing.com-archival#55]
Currently, story choices for non-existent chapters are still formatted as links despite them not actually seemingly containing any hyperlink to go anywhere.

The issue is that the faded-out "links" (which is how it normally distinguishes the story choices between existing and non-existent chapters) is not present if you use any sort of custom webpage coloring, resulting in the story choice "links" for non-existent chapter to be displayed exactly the same as the story choice links for existing chapters.

(I tested this in Pale Moon and LibreWolf; both of which are derivatives of Firefox)

I would think that it would be simple enough to straight-up remove the "non-existent" hyperlink aspect for story choices that do not actually have an existing chapter.

**Comment by Ackater** [comment]
Thanks for the suggestions!

That should be all of them. Let me know if there's anything else
