### ISSUE TITLE
"You must type either y or n. [y/n]:" Infinite Loop

### ISSUE THREAD

**Issue by HyperPeanut** [Ackater/writing.com-archival#6]
When it asks me to confirm my username when logging in, no matter what key I press it keeps giving me the message "You must type either y or n."

I'm running python 3.7.3, I have MechanicalSoup, jinja2, and lxml installed, and I'm on Windows.

**Comment by Ackater** [comment]
684200a should fix this. Can you update and try again

**Comment by ProfHariSeldon** [comment]
I did that and it fixed the problem for me

**Comment by HyperPeanut** [comment]
It worked. Thank you.
