### ISSUE TITLE
MALFORMED ITEM_ID

### ISSUE THREAD

**Issue by ProfHariSeldon** [Ackater/writing.com-archival#7]
I installed Python 3.7.3 to resolve this issue: https://github.com/Ackater/writing.com-archival/issues/5

After "Saving session." I hit the enter key

C:\Users\linux>C:\Users\linux\AppData\Local\Programs\Python\Python37\python.exe D:\Documents\writing\Archives\writing.com-archival-master\run.py get 1258638
Logging in...
Enter your username and password for writing.com.
Enter your username: ##########
you typed ##########. is this correct?
[y/n]:
Enter your password: ########
you typed ########. is this correct?
[y/n]:
Submitted login form.
Saving session.
#!# MALFORMED ITEM_ID: 1258638

**Comment by Ackater** [comment]
Sorry for now, you need the full ID: ```1258638-To-boldly-go```
