### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ProfHariSeldon** [Ackater/writing.com-archival#8]
This is a continuation of https://github.com/Ackater/writing.com-archival/issues/7

C:\Users\linux>C:\Users\linux\AppData\Local\Programs\Python\Python37\python.exe D:\Documents\writing\Archives\writing.com-archival-master\run.py get 1258638-To-boldly-go
### Now archiving 1258638-To-boldly-go
# 1258638-To-boldly-go: Gathering info.
Traceback (most recent call last):
  File "D:\Documents\writing\Archives\writing.com-archival-master\run.py", line 40, in <module>
    args.func(args)
  File "D:\Documents\writing\Archives\writing.com-archival-master\run.py", line 18, in get
    archive(id)
  File "D:\Documents\writing\Archives\writing.com-archival-master\archiver.py", line 77, in archive
    canon_descents, canon_names = get_chapter_list(story_id)
  File "D:\Documents\writing\Archives\writing.com-archival-master\scraper.py", line 112, in get_chapter_list
    url_cutoff = outline_links[0].attrib['href'].rfind("/") + 1
IndexError: list index out of range

**Comment by Ackater** [comment]
I'm unable to reproduce this one. What is your system running?

**Comment by ProfHariSeldon** [comment]
I think I installed Python 64-bit correctly (default Python download from the website is 32-bit and it's hard to find 64-bit there), but it did say AMD64 and I am running an Intel i7.

Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32

Microsoft Windows 10 Home
10.0.17134 Build 17134
ASUS G752VL laptop
Intel i7-6700 HQ CPU

**Comment by Ackater** [comment]
Trying it on my Windows: ```Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32```, I'm unable to reproduce this error. What packages you have installed if you check ```pip list```. Are you on English locale Windows?

Maybe try Windows Subsystem for Linux?

**Comment by ProfHariSeldon** [comment]
One more question: Where does the script download the story to?  I rebooted and it seemed to work, but I can't find the downloaded story files.

C:\WINDOWS\system32>C:\Users\linux\AppData\Local\Programs\Python\Python37\python.exe D:\Documents\writing\Archives\writing.com-archival-master\run.py get 1258638-To-boldly-go
Logging in...
Enter your username and password for writing.com.
Enter your username: ##########
you typed ##########. is this correct?
[y/n]:
Enter your password: ########
you typed ########. is this correct?
[y/n]:
Submitted login form.
Saving session.
### Now archiving 1258638-To-boldly-go
# 1258638-To-boldly-go: Gathering info.
# 1258638-To-boldly-go: Downloading for the first time.
# 1258638-To-boldly-go: 10/89
# 1258638-To-boldly-go: 20/89
# 1258638-To-boldly-go: 30/89
# 1258638-To-boldly-go: 40/89
# 1258638-To-boldly-go: 50/89
# 1258638-To-boldly-go: 60/89
# 1258638-To-boldly-go: 70/89
# 1258638-To-boldly-go: 80/89
# 1258638-To-boldly-go: 89/89
# 1258638-To-boldly-go: Finished!

**Comment by Ackater** [comment]
It looks like you're running it from your system32 folder (which you probably shouldn't do) so it would download to ```C:\WINDOWS\system32\archive```

**Comment by ProfHariSeldon** [comment]
Ok that was my question it downloads to your working directory.
